.TH SABACC 6 "24 December 2008" "" ""

.SH NAME
Sabacc \- an interesting card game similar to Blackjack.

.SH SYNOPSIS
.B "sabacc --help"
.br
.B "sabacc [--local] [--no-gui]"

.SH DESCRIPTION
\fBsabacc\fR is a card game originally from the Star Wars universe. It is similar to Blackjack except it employs a random element where any card may change value at any point in the game.

For more information, please see the Sabacc website at \fIhttp://sabacc.sourceforge.net/\fR.

.SH OPTIONS
\fBsabacc\fR accepts the following options:
.sp
.IP "--help"
Shows a summary of the commands accepted by
.I sabacc
.IP "--local"
Force
.I sabacc
to use local Python packages.
.IP "--no-gui"
Do not use the GTK graphical user interface. Instead use a text-based interface. This is the default for those environments where PyGTK is not installed or is not the correct version.

.SH AUTHOR
This manual page was written by Joel Cross <joel@kazbak.co.uk>.

.SH BUGS
Plenty. Please report any bugs you find using the Launchpad project page.
