.TH SABACC 6 "29 January 2008" "" ""

.SH NAME
Sabacc \- an interesting card game similar to Blackjack.

.SH SYNOPSIS
.B sabacc

.SH DESCRIPTION
\fBsabacc\fR is a card game originally from the Star Wars universe. It is similar to Blackjack except it employs a random element where any card may change value at any point in the game.

For more information, please see the Sabacc website at \fIhttp://sabacc.sourceforge.net/\fR.

.SH OPTIONS
\fBsabacc\fR accepts no options.

.SH AUTHOR
This manual page was written by Joel Cross <joel@kazbak.co.uk>.

.SH BUGS
Plenty. Please report any bugs you find using the Sourceforge project page.
